---
#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
#PV Postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weight-tracker-storage-db
  labels:
    type: local-db
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-storage/pv-postgres"
---    
#PV PgAdmin
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weight-tracker-storage-db-admin
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-storage/pv-pgadmin"
---
#PVC Postgres
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc-postgres
  namespace: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: "local-db"
  resources:
    requests:
      storage: 5Gi
---
#PVC Postgres
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-pgadmin
  namespace: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: "local"
  resources:
    requests:
      storage: 3Gi
---
#Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
 namespace: postgres
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
     containers:
       - name: postgres
         image: postgres:latest
         imagePullPolicy: "IfNotPresent"
         resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "1"
             memory: "4Gi"
         ports:
           - containerPort: 5432
         env:
           - name: POSTGRES_PASSWORD
             value: laredo
           - name: PGDATA
             value: /var/lib/postgresql/data/pgdata
         volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
     volumes:
       - name: postgredb
         persistentVolumeClaim:
           claimName: postgresql-pvc-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  ports:
    - port: 5432
      nodePort: 30201
  selector:
    app: postgres
  type: NodePort

---
#PgAdmin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgres
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4          
          resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "1"
             memory: "4Gi"
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "admin@camilobernal.dev"
           - name: PGADMIN_DEFAULT_PASSWORD
             value: "admin"
           - name: PGADMIN_PORT
             value: "80"
          volumeMounts:
           - mountPath: /var/lib/pgadmin
             name: pgadmin-mnt
          ports:
            - containerPort: 80
              name: pgadminport
      initContainers:
        - name: pgadmin-data-permission-fix
          image: busybox
          command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin"]
          #command: ["sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin"]
          volumeMounts:
          - name: pgadmin-mnt
            mountPath: /var/lib/pgadmin
      volumes:
       - name: pgadmin-mnt
         persistentVolumeClaim:
           claimName: postgresql-pv-pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgres
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
   - port: 80
     nodePort: 30200